### ISSUE TITLE
doesn't stay logged in

### ISSUE THREAD

**Issue by X1011** [elamperti/OpenWebScrobbler#27]
Every time I visit Open Web Scrobbler, I have to log in again. I think this just started happening a month or 2 ago, and I get the following error messages in the console when I log in, so I think Last.fm made a change to their API.

```
2017-04-20 22:19:10.839 auth?api_key=0aa2e9944f3e38f7a64358dde668ff63&cb=http://ows.elamperti.com/callback.php:1 [Report Only] Refused to send form data to 'http://ows.elamperti.com/callback.php?token=<redacted>' because it violates the following Content Security Policy directive: "form-action https: http://www.last.fm".

2017-04-20 22:19:11.245 auth?api_key=0aa2e9944f3e38f7a64358dde668ff63&cb=http://ows.elamperti.com/callback.php:1 [Report Only] Refused to send form data to 'http://ows.elamperti.com/' because it violates the following Content Security Policy directive: "form-action https: http://www.last.fm".
```

**Comment by elamperti** [comment]
@X1011 Thanks for reporting this, I'll look into it

**Comment by wolflambert** [comment]
Yeah I get this too

**Comment by elamperti** [comment]
@X1011 @wolflambert thanks for your reports! The problem was a combination of to the auth URL being called via plain HTTP and not using SSL at the callback URL. I changed my setup to use let's encrypt and now the error is gone and this should be fixed :grin: :tada:

**Comment by wolflambert** [comment]
Have you pushed this to the hosted version yet? I still have to log in every time.

**Comment by elamperti** [comment]
@wolflambert I did, but perhaps that wasn't the problem after all :confused: I just updated the `session.gc_maxlifetime` of my php.ini to two weeks, hopefully that helps. Please let me know if it happens again in the future. Thanks for your patience and help! :slightly_smiling_face:

**Comment by elamperti** [comment]
@wolflambert @X1011 Just made a change on cookie duration because it wasn't working as expected for me. Should finally fix this once and for all :crossed_fingers:

**Comment by wolflambert** [comment]
I haven't had to log in in a couple of days, so I hope it's fixed!

By the way — did you replace https://ows.elamperti.com/manifest.json with my edited version of it? I still can't use the site as a web app on Android

**Comment by elamperti** [comment]
@wolflambert Just updated it, sorry about that. I also opened #33, this project needs some updates :grin:
